#include<iostream>
using namespace std;
int main()
{
    int t,n;
    cin>>t;
    while(t--)
    {
        cin>>n;
        if(n==1)
            cout<<1<<endl;
        if(n==11)
            cout<<3<<endl;
        if(n==111)
            cout<<6<<endl;
        if(n==1111)
            cout<<10<<endl;
        if(n==2)
            cout<<11<<endl;
        if(n==22)
            cout<<13<<endl;
        if(n==222)
            cout<<16<<endl;
        if(n==2222)
            cout<<20<<endl;
        if(n==3)
            cout<<21<<endl;
        if(n==33)
            cout<<23<<endl;
        if(n==333)
            cout<<26<<endl;
        if(n==3333)
            cout<<30<<endl;
        if(n==4)
            cout<<31<<endl;
        if(n==44)
            cout<<33<<endl;
        if(n==444)
            cout<<36<<endl;
        if(n==4444)
            cout<<40<<endl;
        if(n==5)
            cout<<41<<endl;
        if(n==55)
            cout<<43<<endl;
        if(n==555)
            cout<<46<<endl;
        if(n==5555)
            cout<<50<<endl;
        if(n==6)
            cout<<51<<endl;
        if(n==66)
            cout<<53<<endl;
        if(n==666)
            cout<<56<<endl;
        if(n==6666)
            cout<<60<<endl;
        if(n==7)
            cout<<61<<endl;
        if(n==77)
            cout<<63<<endl;
        if(n==777)
            cout<<66<<endl;
        if(n==7777)
            cout<<70<<endl;
        if(n==8)
            cout<<71<<endl;
        if(n==88)
            cout<<73<<endl;
        if(n==888)
            cout<<76<<endl;
        if(n==8888)
            cout<<80<<endl;
        if(n==9)
            cout<<81<<endl;
        if(n==99)
            cout<<83<<endl;
        if(n==999)
            cout<<86<<endl;
        if(n==9999)
            cout<<90<<endl;
    }
}
